spring:
  datasource:
    url: jdbc:oracle:thin:@172.20.195.208/orcl
    username: shxx
    password: 123
    driverClassName: oracle.jdbc.driver.OracleDriver

logging:
  level:
     com.zyjg.adtech.bigscreen.mapper: DEBUG


